AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CFNCrawlerName:  
    Type: String
    Default: cfn-crawler-bolsafamilia
    Description: O nome do nosso crawler
  CFNDatabaseName:
    Type: String
    Default: cfn-database-bolsafamilia
    Description: O nome do banco de dados
  CFNTablePrefixName:
    Type: String
    Default: cfn_bolsafamilia_
    Description: prefixo que o crawler deve atribuir a nossa tabela 
  BucketURI:
    Type: String
    Default: "s3://[EDITE AQUI. COLOQUE O NOME DO SEU BUCKET]/raw/"
    Description: O nosso bucket onde o arquivo do bolsa familia estah.
  RoleARN:
    Type: String
    Default: "[EDITE AQUI. Ex.: arn:aws:iam::9876543210:role/gluelab]"
    Description: A role que usaremos pra que o crawler consiga fazer o manejo tanto do S3 quanto do Glue Catalog.
Resources:
  # Criacao do database que será o container da tabela criada pelo crawler
  CFNDatabaseBolsaFamilia:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref CFNDatabaseName
        Description: "Database container da tabela criada pelo crawler a partir da base do bolsa familia"
  # Criacao do crawler
  CFNCrawlerBolsaFamilia:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CFNCrawlerName
      Role: !Ref RoleARN
      #Classifiers: nenhum, vamos usar o default
      Description: AWS Glue crawler to crawl weather data
      #Schedule: nenhum, vamos usar o default run-on-demand
      DatabaseName: !Ref CFNDatabaseName
      Targets:
        S3Targets:
          # O caminho para o bucket
          - Path: !Ref BucketURI
      TablePrefix: !Ref CFNTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"